name: base-project

networks:
  base-project-network:
    driver: bridge

services:
  app-instance1:
    container_name: app-instance-1
    image: app-base-project:1.0
    environment:
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - base-project-network

  app-instance2:
    container_name: app-instance-2
    image: app-base-project:1.0
    environment:
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - base-project-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - base-project-network
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app-instance1
      - app-instance2
